---
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - test/dummy/db/schema.rb
    - test/dummy/db/migrate/*.rb
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - .git/**/*

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - test/integration/spina/conferences/primer_theme/pages_navigation_test.rb
    - test/integration/spina/conferences/primer_theme/conferences/conferences_navigation_test.rb

Layout/LineLength:
  Exclude:
    - test/dummy/db/seeds.rb

Metrics/MethodLength:
  Exclude:
    - test/integration/spina/conferences/primer_theme/conferences/pages_navigation_test.rb
    - test/integration/spina/conferences/primer_theme/conferences/conferences_navigation_test.rb

Naming/VariableNumber:
  Exclude:
    - test/**/*
