---
env:
  es6: true
  browser: true
parserOptions:
  sourceType: module
extends: 'eslint:recommended'
parser: babel-eslint
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
